PERMISSION_IMPORT = "data_import"
PERMISSION_MANAGEMENT = "data_management"
PERMISSION_ANALYSIS = "data_analysis"
PERMISSION_ADMIN = "user_admin"

ALL_PERMISSIONS = [
    PERMISSION_IMPORT,
    PERMISSION_MANAGEMENT,
    PERMISSION_ANALYSIS,
    PERMISSION_ADMIN,
]

PERMISSION_LABELS = {
    PERMISSION_IMPORT: "数据导入",
    PERMISSION_MANAGEMENT: "二返数据管理",
    PERMISSION_ANALYSIS: "二返数据分析",
    PERMISSION_ADMIN: "用户权限管理",
}
